### ISSUE TITLE
Error at Building

### ISSUE THREAD

**Issue by greco2017** [ibm-research/ecdaa#1]
Hello!
We use ubuntu 17.04 and installed java 1.8.0_131 and maven-3.2.2 . 
We executed at first the command **mvn clean package** ,but we get the following **error**:
Failed to execute goal on project ecdaa: Could not resolve dependencies for project com.ibm.zurich:ecdaa:jar:1.0.3: The following artifacts could not be resolved: at.tugraz.iaik:jce:jar:5.3, at.tugraz.iaik:eccelerate:jar:4.01: Failure to find at.tugraz.iaik:jce:jar:5.3 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Should we execute other command first? How can we deal with this ?

Thanks a lot!

**Comment by manudrijvers** [comment]
Did you install the IAIK library first? See https://github.com/ibm-research/ecdaa#installing-iaik for the two commands.

**Comment by greco2017** [comment]
Hello! thanks for your response! 
No we didn't install the library first. We will try this right now and we will inform you for the progress.
Thanks a lot!

**Comment by greco2017** [comment]
Hello! We executed 1) mvn install:install-file -Dfile=iaik/iaik_jce.jar -DgroupId=at.tugraz.iaik -DartifactId=jce -Dversion=5.3 -Dpackaging=jar
2)mvn install:install-file -Dfile=iaik/iaik_eccelerate.jar -DgroupId=at.tugraz.iaik -DartifactId=eccelerate -Dversion=4.01 -Dpackaging=jar
3) mvn clean package
and everything is ok.
After we excuted the command  java -jar target/ecdaa-x.x.x-jar-with-dependencies.jar -ikeygen ipk isk rl -usecurve TPM_ECC_BN_P256  
and then we get the following error **Error: Unable to access jarfile target/ecdaa-x.x.x-jar-with-dependencies.jar**

How can we deal with it?
Thanks a lot!

**Comment by manudrijvers** [comment]
Did you replace x-x-x with the current version number?

**Comment by greco2017** [comment]
Thank you for your response! 
The current version is 1.0.3 ,right?

**Comment by greco2017** [comment]
We executed the comand **java -jar target/ecdaa-1.0.3-jar-with-dependencies.jar -ikeygen ipk isk rl -usecurve TPM_ECC_BN_P256** in the main file ecdaa-master and successfully executed!

Thank you very much!

**Comment by manudrijvers** [comment]
Perfect, glad it worked.
