### ISSUE TITLE
BNCurve.hashModOrder can return negative

### ISSUE THREAD

**Issue by zanebeckwith** [ibm-research/ecdaa#2]
In `BNCurve.hashModOrder`, the `BigInteger` is constructed from the hash output without specifying the signum argument to the constructor. Because `BigInteger` is two's-complement, if the hash output happens to start with a 1-bit, the `BigInteger` constructor will then interpret this as a negative number (though we assume all numbers are positive).

This is problematic because the result of the `mod(this.getOrder())` operation, for the same byte array, will produce a different `BigInteger` if the hash is interpreted as a negative number.

**Comment by manudrijvers** [comment]
Good catch, thanks Zane!
