### ISSUE TITLE
ECDAA approved curves

### ISSUE THREAD

**Issue by AnnaAnge** [ibm-research/ecdaa#4]
In this implementation and also in most documents concerning ECDAA (TPM and FIDO specs) i've noticed that the curves used are BN. 
Is there a specific reason we do not use NIST curves instead? Is it not allowed or just a recommendation? 

Thanks a lot,
Anna

**Comment by manudrijvers** [comment]
The cryptographic scheme requires so-called "pairing-friendly curves" (see e.g. [wikipedia](https://en.wikipedia.org/wiki/Pairing-based_cryptography)), which BN curves are. As far as I know, NIST doesn't have any pairing-friendly curves.

**Comment by AnnaAnge** [comment]
Ok i get it now.
Thanks a lot!!
